- name: install web component
  hosts: web
  become: yes
  tasks:
  - name: Insstall nginx 
    ansible.builtin.yum:
      name: nginx
      status: installed
  
  - name: start nad enable nginx
    ansibile.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      satus: absent
  
  - name: cretae html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      satus: directory

  - name: downlaod the archieve
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      path: /tmp

  - name: unarchive the file 
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: copy the roboshop.conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: restart the service
    ansible.builtin.service:
      name: nginx
      state: restarted